language: python
python:
  - "3.13"  # Replace with your Python version

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

# Run the test suite, format and lint checks
script:
  - black --check .
  - flake8
  - coverage run --source=<your_project_name> manage.py test  # Replace <your_project_name>
  
# Report code coverage
after_success:
  - coveralls
