language: python
python:
  - "3.8"

install:
  - pip install setuptools==59.6.0
  - pip install awsebcli
  - pip install -r requirements.txt


script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_scripts:
- coveralls
